app:
  ai:
    provider: deepseek
    # ollama or deepseek

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: autominutes_backend
  ai:
    model:
      chat: openai
      # ollama or openai
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 2000ms
        multiplier: 5
    openai:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:2b

  datasource:
    url: jdbc:postgresql://localhost:5432/autominutes
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


security:
  jwt:
    secret: ${JWT_SECRET_BASE64:QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo5ODc2NTQzMjEwQUJDREVG}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

logging:
  level:
    org:
      springframework:
        ai: DEBUG